//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlHrsConsultoria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacion
    {
        public int idOperacion { get; set; }
        public string nombre { get; set; }
        public Nullable<int> idModulo { get; set; }
    
        public virtual Modulo Modulo { get; set; }
    }
}
