//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlHrsConsultoria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto_Consultor_Cliente
    {
        public int idDetalle { get; set; }
        public Nullable<int> idProyecto { get; set; }
        public Nullable<int> idConsultor { get; set; }
        public Nullable<int> idPerfil { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<decimal> montoPrecio { get; set; }
        public Nullable<decimal> costo { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFinal { get; set; }
        public Nullable<decimal> cantidadHrs { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Consultor Consultor { get; set; }
        public virtual Perfil Perfil { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
